name = "hello-world-broken-forest-d7bd"
type = "javascript"
account_id = "a5a92e57f7c6a51093123be9dc525d2a"
compatibility_date = "2023-06-23"

[build]
command = "npm run build"
main = "./.next/server/pages/index.js"

[site]
bucket = "./public"
entry-point = "./.next/server/pages/index.js"
